doctrine_migrations:
    migrations_paths:
        'DoctrineMigrations': '%kernel.project_dir%/src/Migrations'
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        #namespace: DoctrineMigrations
    organize_migrations: BY_YEAR_AND_MONTH # Version >= 1.2, possible values are: "BY_YEAR", "BY_YEAR_AND_MONTH", false
